### ISSUE TITLE
PostgreSQL is not in control panel

### ISSUE THREAD

**Issue by rrjanbiah** [WPN-XM/WPN-XM#196]
Unlike Nginx, PHP, etc.. PostgreSQL is not listed in control panel---even if we use BigPack installer.

If there's any hidden hack (say, ini file or so) available for it, please document it.

**Comment by rrjanbiah** [comment]
I still can't seem to find it in control panel version 0.8.0? Should I enable it anything else?

**Comment by jakoch** [comment]
I'm sorry. This is my fault.
The postgresql installation detection failed, so no buttons where rendered.
They are now added and properly connected. The autostart has also been updated.

One problem remains:
I can't get process monitoring after calling "pg_ctl start" in start command "startPostgreSQL",
because "pg_ctl" is only a launcher and it will shutdown. That means that the PostgreSQL process monitoring must be done via the PID file. But this doesn't work, yet.

For details of the changes, please take a look at the commits containing "postgresql": https://github.com/WPN-XM/server-control-panel/commits/master

**Comment by rrjanbiah** [comment]
Thanks for your quick update

**Comment by jakoch** [comment]
I hope i got all issues: 
- [ ] Postgres autostart
- [ ] Postgres process detection
  - [ ] on shutdown, PID deletion
  - [ ] on continue, activation status transfer to mainwindow
- [ ] buttons connected and events hooked up
