### ISSUE TITLE
PHP stops working from time to time, WPN-XM should keep it always online

### ISSUE THREAD

**Issue by duzun** [WPN-XM/WPN-XM#322]
PHP stops working quite often. While using other software (eg Winginx) I never had this issue.
WPN-XM should keep PHP always online.

My Environment:
OS: **Win 8.1 x64 ru**
PHP: **5.6.5 x64 single threaded**
WPN-XM: **0.8.0**
Error logs: **none**

**Comment by klonos** [comment]
This is not helpful. Environment (OS and architecture for example)? Error logs?

**Comment by jakoch** [comment]
Thank you for reporting this issue, Dumitru.

The issue about PHP crashes and instability came up before, see https://github.com/WPN-XM/WPN-XM/issues/202 
As mentioned in the posts there, one solution would be to hide the crashes by using services https://github.com/WPN-XM/WPN-XM/issues/165

An PHP crash dump, trace or error log would be nice.

> While using other software (eg Winginx) I never had this issue.
Ok, that brings up the question: what do they do differently?
A short look at their configuration doesn't reveal anything.
Maybe they use services to start the PHP daemon or monitor the daemon from the Tray app.
But who knows ... except Alexey, because Winginx is not open-source.

I can not raise the major version to stable, if the stack still has this issue.
This issue must be solved before v1.0.0.
I will put a strong focus on this issue, after finishing the next release.
I'm also looking forward receiving contributions, which tackle this problem.

**Comment by jakoch** [comment]
Ok, i took a look at Winginx again.
They have a tool around called "spawn-fcgi". Originally, this tool comes from the lighttpd web server.
I'm not sure, if PHP runs more stable if daemons are started that way.
http://wiki.habariproject.org/en/Installation_using_Nginx

**Comment by duzun** [comment]
There is no error in the error log.
At first I thought there is something wrong with my PHP source code, but it crashes while running two different frameworks - one is very complex and the other one is very simple.
I ran same version of PHP as a service using `winsw.exe` and it still keeps crashing (service just stops without any error in the logs).
I upgraded to PHP 5.6.5, same thing, with WPN-XM and as a service it just stops. Sometimes after 10 min of working, sometimes after 2 hours. The more request I run, the quicker it stops.

I don't know what winginx does, but I notice it spawns three processes for each version of PHP. It might be `spawn-fcgi`.

No matter what the issue is (and there might be many issues with PHP and extensions), I think WPN-XN should keep PHP always running.

I also think it would be nice to have more PHP processes running, otherwise it gets very slow while developing heavy PHP applications. One of my projects makes a lot of request to PHP at any page load (JS, CSS, Images, AJAX requests all go through PHP) and with one PHP process it load the page in about 10 sec, while with more PHP processes it loads in only 3 sec.

I'll be more then happy to help when I have more free time.

**Comment by duzun** [comment]
I like the idea of `spawn-fcgi`.
I'll do some experiments with it later on.
I'm going to run PHP as a service with `winsw.exe` and `spawn-fcgi.exe` and see what happens.
In the case it works good, I'll post back my results here.

**Comment by duzun** [comment]
It looks like `spawn-fcgi` does its job quite good.
I couldn't run it as a service, I guess because the `spawn-fcgi` process exists immediately after it spawns PHP child processes.
But I managed to create a `start-php.cmd` that spawns few PHP processes:

```batch
REM start-php.cmd
@echo off
set _dir=%~dp0
set PHPRC=%_dir%\php.ini
spawn-fcgi -f "%_dir%\php-cgi.exe" -a 127.0.0.1 -p 9056 -C 6 -F 4 -P "%_dir%..\temp\php.pid"
```

And here is my `stop-php.cmd` file:

```batch
REM stop-php.cmd
@echo off
taskkill /f /IM php-cgi.exe
```

My `stop-php.cmd` is not perfect, cause it kills any `php-cgi.exe` process.
It is possible to catch all PIDs that `spawn-fcgi` forks and kill only them when user stops PHP.

I guess Winginx does the same.

**Comment by jakoch** [comment]
Thanks you for testing, Dumitru! 
This is very valuable information for me.

> I ran same version of PHP as a service using winsw.exe and it still keeps crashing (service just stops without any error in the logs).

This is really odd. Maybe i should request help from the PHP team to help us track this down.
PHP is not stable on Windows - and it's somehow related to sockets/cgi/spawning.

> I also think it would be nice to have more PHP processes running

:+1:  This is a feature request. I will open a new issue for this.
I think i will add multiple configurations, so that the user can select, if he wants to run one, two or a pool of php daemons. Nginx would act as a balancer and distribute requests to the pool, like described here: https://github.com/WPN-XM/WPN-XM/issues/202#issuecomment-45089295
This will improve the performance a lot.
But it will not change a thing in regard to stability, because the whole pool crashes.

> My stop-php.cmd is not perfect, cause it kills any php-cgi.exe process.

Yes, we do the same currently with the WPN-XM SCP and start/stop scripts.
It's not really good, but works. In the future, i want to do a more fine-grained shutdown, maybe related to the WPN-XM folder. So that the stack is only responsible for the daemons living inside it's own folder structure. I'm open for ideas in this area.

- I found the source-code of spawn-fcgi over at https://github.com/lighttpd/spawn-fcgi/blob/master/src/spawn-fcgi.c
The main functions are bind_socket and fcgi_spawn_connection, the rest is argument handling and permissions. I will take a closer look at this, maybe i can incorporate some parts into the SCP.

**Comment by mindplay-dk** [comment]
I'm experiencing random shutdown of php-fpm under Win 8.1 x64 as well, on two different systems - nothing appears in the log, no error message anywhere, the service just shuts down quietly.

I am able to repeat the crashes by just firing concurrent requests at the server, e.g. `ab -n 1000 -c 20` will make it crash almost every time - this is with two different codebases on two different systems.

Perhaps an upgrade from 5.6.6 to 5.6.9 is worth attempting first thing? Could be this has been fixed already. Unlikely though - the PHP team tends to not care much about the Windows build...

**Comment by jakoch** [comment]
> Unlikely though - the PHP team tends to not care much about the Windows build...

Rumors say so.. but they care - or maybe i'm just an optimist.
The real downside is, that there are only a few guys working "actively" on the Windows parts (Pierre, Anatol).

If someone, properly identifies the issue in a reproducible manner, it won't be a problem to get a fix into the core. I still think this/these issue are CGI related - but that's just guessing around.

If you can get segfaults or a back trace from PHP, so that we can narrow it down to code and open a bugreport over at php.net. 
You will need the [Debug Pack](http://windows.php.net/download/) and a diag tool, like [Debug Diagnose](https://www.microsoft.com/en-us/download/details.aspx?id=40336).
Referencing: https://bugs.php.net/bugs-generating-backtrace-win32.php

This whole procedure of tracing a PHP crash on Windows is still a high barrier.

Btw: i've already added "LiteRC" installers to test PHP Release Candidates versions.
The next step is to provide the tools to do backtraces for PHP out-of-the-box.
That means to add the matching "Debug Pack", a "Diagnose Tool" and "ab".
Not sure, if i'm able to redistribute the "Microsoft Debug Diagnostic Tools", 
but there should be alternatives.

**Comment by mindplay-dk** [comment]
Okay, the plot thickens. This is weird. Really, really weird.

So if I run `ab -n 1000 -c 20`, fpm shuts down consistently after between 500-519 requests.

But if I run `ab -n 1000 -c 1`, it shuts down after *precisely* 500 requests, *every time*.

It's like there's a hard 500 request limit built into this binary and it just consistently stops when it reaches that number.

I wonder if somebody left a diagnostic statement in there somewhere checking for the number of request to reach 500 or something?? Really that's my best guess ;-)

Why 500? Precisely 500 - every time, consistently repeatable. Why?

**Comment by jakoch** [comment]
You are running into the FCGI_MAX_REQUEST limit.
The PHP FastCGI processes exit after handling 500 requests by default.
It may exit later (at any time), if more requests are made. 
So you could end up with "517 requests + hit limit + exit".
This event is an error, which should be logged and is reported as "500 Internal Server Error" to the client.

You should not hit a limit of 500, because of `fastcgi_param  PHP_FCGI_MAX_REQUESTS 1000;` in `nginx.conf`. But the directive seems to be ignored, when set from Nginx Config
https://github.com/WPN-XM/WPN-XM/blob/master/configs/nginx.conf#L132

----

If the directive is set on the ENV: `SET PHP_FCGI_MAX_REQUESTS=0`

`start-wpnxm.bat`
```
:start-php
    echo Starting PHP FastCGI...
    set PHP_FCGI_MAX_REQUESTS=0
    set PHP_FCGI_CHILDREN=2
    %HIDECONSOLE% %cd%\bin\php\php-cgi.exe -b 127.0.0.1:9100 -c %cd%\bin\php\php.ini
    echo.
goto END
```

`index.php`
```
<?php echo 'Hello World!';
```

```
> WeigHTTP.exe -n 20000 -c 20 -t 2 http://localhost/index.php

WeigHTTP - Version 0.3 (Win32)
A lightweight and simple webserver benchmarking tool...

Starting benchmark...

Spawning thread #1: 10 concurrent requests, 10000 total requests.
Spawning thread #2: 10 concurrent requests, 10000 total requests.
Progress:  10% done.
Progress:  20% done.
Progress:  30% done.
Progress:  40% done.
Progress:  50% done.
Progress:  60% done.
Progress:  70% done.
Progress:  80% done.
Progress:  90% done.
Progress: 100% done.

Finished in 9 sec, 704 millisec and 0 microsec,
            2061 req/s, 456 kbyte/s.

Requests: 20000 total, 20000 started, 20000 done,
          20000 succeeded, 0 failed, 0 errored.

Status codes: 20000 2xx, 0 3xx, 0 4xx, 0 5xx.

Traffic: 4540000 bytes total, 4120000 bytes http, 420000 bytes data.
```

```
> WeigHTTP.exe -n 50000 -c 200 -t 2 http://localhost/index.php

WeigHTTP - Version 0.3 (Win32)
A lightweight and simple webserver benchmarking tool...

Starting benchmark...

Spawning thread #1: 100 concurrent requests, 25000 total requests.
Spawning thread #2: 100 concurrent requests, 25000 total requests.
Progress:  10% done.
Progress:  20% done.
Progress:  30% done.
Progress:  40% done.
Progress:  50% done.
Progress:  60% done.
Progress:  70% done.
Progress:  80% done.
Progress:  90% done.
Progress: 100% done.

Finished in 25 sec, 40 millisec and 0 microsec,
            1996 req/s, 442 kbyte/s.

Requests: 50000 total, 50000 started, 50000 done,
          50000 succeeded, 0 failed, 0 errored.

Status codes: 50000 2xx, 0 3xx, 0 4xx, 0 5xx.

Traffic: 11350000 bytes total, 10300000 bytes http, 1050000 bytes data.
```

But this doesn't change a thing in regard to the two issues (when a limit is set):
- when the limit is hit there is no error logged. it's empty.
- recycling / respawning never happens.

**Comment by mindplay-dk** [comment]
@jakoch got it, thanks! added a global environment variable `PHP_FCGI_MAX_REQUESTS=0` and it's working now. (this being a dev server, I don't worry about memory fragmentation etc.)

Off-topic, but my other big problem with this new stack is [this issue](https://github.com/sebastianbergmann/php-code-coverage/issues/342) which I suspect could be either the Windows build of PHP 5.6 or xdebug. (or php-code-coverage itself of course, I'm waiting to hear back from Sebastian Bergmann.)

**Comment by jakoch** [comment]
Glad to hear that it's working now!

I will add the directive to the SCP start, too. 

Mem-wise: yes, that's why i initially set 1000.
Anyway: disabling max requests is not that bad for a "dev" stack.

--

In regard to your "php-code-coverage" issue: 
From the stack-perspective i can only advise to (a) check the components xdebug and php for compatibility and (b) apply some performance tweaks to PHP and Xdebug. 

PHP: By default the OpCode Cache is disabled for PHP56 (https://github.com/WPN-XM/WPN-XM/blob/master/configs/php/php56.ini-dev#L1887). If not already done, set `opcache.enable=1` in php.ini and tweak some of the other values to get a speed-up. Not sure, if this helps.
Xdebug: You can also play around with XDEBUG_CC_UNUSED, XDEBUG_CC_DEAD_CODE.

**Comment by mindplay-dk** [comment]
On the code coverage issue, I downgraded to xdebug 2.2.7 (latest 2.2 release) and the performance problem is gone. (XAMPP still distributes their stack with xdebug 2.2, I wonder if this is the reason.)

**Comment by jakoch** [comment]
Glad you solved that issue, too. 
Maybe related: http://bugs.xdebug.org/view.php?id=1123
