### ISSUE TITLE
Errors trying to run SSL using the Webinstaller php54 w32

### ISSUE THREAD

**Issue by frequent** [WPN-XM/WPN-XM#332]
Hey,

I just updated my WPN-XM using the Webinstaller for [php version 5.4 w32](http://wpn-xm.org/downloads/WPNXM-0.8.0-Webinstaller-Setup-php54-w32.exe) and I'm having some issues trying to get things back working.

Namely these:
- SSL includes spdy, but the underlying module seems missing

If I find other things I will post here.

Thanks

**Comment by jakoch** [comment]
Hey Sven,

i think, this issue is related to the OpenSSL component. 
I switched the builds lately. Formerly the stack used builds from ShiningLight: https://slproweb.com/products/Win32OpenSSL.html
The new builds are from http://indy.fulgan.com/SSL/ and more "up-to-date" and "not changing the versioning scheme on files with every other release".

But, with this change i introduced a odd BC-break, because the old webinstaller handles the installation of executables, but fetches the latest openssl package from the registry, which is a "zip".
That's why the installation of OpenSSL fails.

The "workaround" is: do a manual installation of OpenSSL into `/bin/openssl`, until the next webinstaller is released. The new release comes in the next days. I'm in the middle of getting deployment from travis to github working.

This BC-break affects only the webinstallers.
The static installers have the old install procedure and the old package included.

- [ ] remove old webinstallers with the next release

> If I find other things I will post here.

Thank you, for your feedback and your donation!

**Comment by jakoch** [comment]
The offical Windows builds do not have the ngx_http_spdy_module build in.
Even if you have SSL certs set up and spdy enabled in nginx.conf, you would run into the following error:
```
[emerg] xy: the "spdy" parameter requires ngx_http_spdy_module in C:/wpnxm/bin/nginx/conf/nginx.conf:162
```

I guess, you replaced nginx with a custom build.

**Comment by frequent** [comment]
I'm not using a custom Nginx build. I only updated my old version of WPN-XM to latest possible, uninstalled all, re-installed. It's the PHP version 5.4 (because on that machine I'm still running XP). Maybe helps.

**Comment by jakoch** [comment]
What i wanted to say: "I guess, you replaced nginx with a custom build back in the days."
Maybe you used this one: http://nginx-win.ecsds.eu/

I doubt that any old version of the offical Nginx Windows (which are used by the WPN-XM installers) had the SPDY module build in.

**Comment by jakoch** [comment]
Ok, feedback here. I'm closing this, because i can not do a thing here.
The windows version of Nginx doesn't include the SPDY module.
Unless i find the time to compile it in, you will have to use a third party Nginx drop-in replacement.
Closing for now.
