### ISSUE TITLE
Control Panel Crashes on continuing process-shutdown-dialog

### ISSUE THREAD

**Issue by mihawk90** [WPN-XM/WPN-XM#349]
Soo... this took me a while to figure out why this is happening to me since it used to run just fine, but I finally got it (yay).

This is an issue that happens with a custom MariaDB (or MySQL) installation. I have my MariaDB set up as a service to start with Windows Boot, now when trying to start WPN-XM I get the "processes are already running" window, with the option to either shutdown the process(es) or continue without. When pressing continue the Control Panel crashes (standard Windows "Application has stopped working" window) and I can't get it to start without manually stopping the service.

This used to work just fine (even tho I wish there was a possibility to skip that dialog, since I know the process is running), but it won't work anymore. I can't say which version broke it, since I skipped a few, but I'm currently running 0.8.0 (Lite Installer).

I have none of the services set to start on control-panel start (just to see if it was an issue). I also reinstalled a few times with the same result. For now I'm using the start-wpnxm.bat (with mariadb and browser lines deleted) and it's working fine.

**Comment by jakoch** [comment]
Thank you for reporting this. This issue came up before and was already fixed.
Sorry, that the new relase took so long, but i had to rewrite toolchain for builds on Travis-CI.

You find the new release here: https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.1

If you want to keep your v0.8.0 you might just drop a new ServerControlPanel in.
You find it over at https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.1
The boxed zips are one-file executables - just unzip into the root folder.

Please give me a feedback, if the new SCP solved this issue.
If you encounter other problems, please keep me updated. I will address them asap.

**Comment by mihawk90** [comment]
Doesn't seem like it worked, but I'm a little confused since the Window Title and "About" button still says 0.8.0.

Aside of that, isn't this a full setup (I used WPNXM-0.8.1-Lite-Setup-php56-w64.exe)? Because after I reinstalled with it, there were a lot of files missing, including the actual control panel, nginx (only some of the conf files installed), mariadb (only my.ini installed) and php (only some bats and php.ini installed), even though the installer says it would need ~250MB of space...

---

OK I just used the boxed zip package and that version is working perfectly fine :) Thanks

**Comment by jakoch** [comment]
Ok, so the initial issue is resolved in v0.8.1 of the server control panel.

> Aside of that, isn't this a full setup (I used WPNXM-0.8.1-Lite-Setup-php56-w64.exe)?
I need to test the installer. Did you do a fresh install or installed on top of 0.8.0?

**Comment by jakoch** [comment]
Ok, i tested WPNXM-0.8.1-Lite-Setup-php56-w64.exe - the installer works.
