### ISSUE TITLE
Control panel titel

### ISSUE THREAD

**Issue by kokpit** [WPN-XM/WPN-XM#409]
I think the name in/on the control panel is written wrong: WP(И)-XM
![image](https://cloud.githubusercontent.com/assets/12991536/8273280/d0538a50-1866-11e5-88f0-fcc26c198d21.png)

**Comment by klonos** [comment]
If you are referring to the "reversed" N ([Cyrillic I](https://en.wikipedia.org/wiki/I_(Cyrillic))), than that is intentional. Let me refer you to [the project's website](http://wpn-xm.org/) and the logo of the application that you'll find there:

![wpn-xm_website-logo](https://cloud.githubusercontent.com/assets/2423362/8273673/eee8a6d6-18ba-11e5-9635-8cbfdd308afa.png)

...as well as here on github (project description and readme file):

![wpn-xm_github-description](https://cloud.githubusercontent.com/assets/2423362/8273675/f81f8968-18ba-11e5-8993-1edf729c6798.png)

![wpn-xm_github-readme](https://cloud.githubusercontent.com/assets/2423362/8273678/fe47aabe-18ba-11e5-8947-a45d09bdc1fc.png)

**Comment by jakoch** [comment]
Thank you for using WPN-XM. 
The "reversed" N is cyrillic and the initial letter for Nginx.
