### ISSUE TITLE
Database Error after upgrading, InnoDB tables error: doesn't exist at the engine

### ISSUE THREAD

**Issue by semplon** [WPN-XM/WPN-XM#460]
I've just upgrading WPN-XM to the latest version. All daemon are working well. But the problem is all of my database structure are gone. I can't access it. the error reporting is : 
```
[Warning] InnoDB: Cannot open table db_name/table_name from the internal data dictionary of InnoDB though the .frm file for the table exists. See http://dev.mysql.com/doc/refman/5.6/en/innodb-troubleshooting.html for how you can resolve the problem.
```

I'm install it as portable. And now, I can't work and all of my projects are gone. I 've to create and reverse back to create the structure. 

I hope this problem can be made as consideration. 

Thanks

**Comment by jakoch** [comment]
Hey Puguh,

that's odd. The most common reason you'll see data dictionary errors like these pop up, is because something was moved around, modified or overwritten. Here the data dictionary expects a file or tablespace to be here, but it isn't. 

To resolve this error, you might try examining the .frm file and recreating the table structure.
I hope that you can recreate the tables.

My advise is to always create a backup of projects and databases, before you install or upgrade.
The state of the upgrade handling is that it's basically an installation on top of the existing installation, where only some daemon configuration files are renamed (to keep the old ones).

Regarding the development of the stack, i would like to point out the open issues and feature requests for improving the upgrade handling. 
- Add Upgrade handling to the installers - #441 
- Do MySQL database dump/reimport during upgrading - #361 
I will try to implement them in one of the next versions. Feel free to support the development.

**Comment by semplon** [comment]
that's what happen with me. please check the installer during the upgrade. after the upgrade is done. the ibdata1 size was just like a new install, around 12 MB. it looks like it had been overwritten during the upgrade. by this mean that my innodb tables are gone. 

I've searching at google about this problem. and since the ibdata1 was changed i can't get the tables structure or data. 

please add new capabilities when upgrade to rename the old ibdata1 or just leave it as it, don't overwritten it. 

Thank You,

**Comment by jakoch** [comment]
Closing in favor of issue https://github.com/WPN-XM/WPN-XM/issues/441. The work is done over there.

**Comment by xieyezi** [comment]
I also have this problem,after upgrade mysql by Homebrew. How is the solution finally?
