### ISSUE TITLE
MariaDB default character set and collation should be UTF-8

### ISSUE THREAD

**Issue by slikts** [WPN-XM/WPN-XM#462]
MariaDB uses `latin1` and `latin1_swedish_ci` character set and collation by default, which can cause problems if any databases created with that default need to be changed to UTF-8. Changing it to `utf8` and `utf8_general_ci` would mean one less annoying setting to configure before using MariaDB.

**Comment by jakoch** [comment]
Hey slikts,

i remember that we had an UTF-8 related issue before.
Let's check how we changed the MariaDB config:
mysqld - https://github.com/WPN-XM/WPN-XM/blob/master/configs/mariadb/my.ini#L49
client - https://github.com/WPN-XM/WPN-XM/blob/master/configs/mariadb/my.ini#L26

- I don't know exactly if i have to set `init-connect='SET NAMES utf8'` for mysqld.

We could probably add `default-character-set=utf8` into the mysql section, too.

What are your suggestions?

**Comment by jakoch** [comment]
The truth is i can not reproduce the issue.

![default-utf8](https://cloud.githubusercontent.com/assets/85608/9555241/1b2542ae-4dcc-11e5-8878-b62483325b85.png)

**Comment by klonos** [comment]
> Changing it to ```utf8``` and ```utf8_general_ci``` would mean one less annoying setting to configure before using MariaDB.

Yes! ...pretty please with cherry on top. So annoying to have to set this for every db I create.

> i remember that we had an UTF-8 related issue before, but i wonder a bit how ```latin1``` and ```latin1_swedish_ci``` sneaked back in the game.

As far back as I can recall with both MySQL as well as with MariaDB, this has always been the default - never saw a different default collation.

**Comment by jakoch** [comment]
Additions:
- `[mysqld] init-connect='SET NAMES utf8'`
- `[mysqldump] default-character-set=utf8`
- `[mysql] default-character-set=utf8`

**Comment by DigiTester** [comment]
I have this issue, and I am fairly sure the latin settings are coming from the build options. 

      MariaDB [myalarm]> SHOW VARIABLES LIKE 'collat%';
      +----------------------+-------------------+
      | Variable_name        | Value             |
      +----------------------+-------------------+
      | collation_connection | utf8_general_ci   |
      | collation_database   | utf8_unicode_ci   |
      | collation_server     | latin1_swedish_ci |
      +----------------------+-------------------+

      MariaDB [myalarm]> SHOW VARIABLES LIKE 'char%';
      +--------------------------+----------------------------+
      | Variable_name            | Value                      |
      +--------------------------+----------------------------+
      | character_set_client     | utf8                       |
      | character_set_connection | utf8                       |
      | character_set_database   | utf8                       |
      | character_set_filesystem | binary                     |
      | character_set_results    | utf8                       |
      | character_set_server     | latin1                     |
      | character_set_system     | utf8                       |
      | character_sets_dir       | /usr/share/mysql/charsets/ |
      +--------------------------+----------------------------+

Apparently collation_server and character_set_server are set when the system is built, but since we just installed the default setup for Centos 6 It would appear that that is build with swedish instead of utf8. Unfortunately overriding that requires changing the mysqld command line. So I've edited /etc/rc.d/init./mysql and added to the "other_args" variable that gets passed to mysqld:

      other_args="$* --character-set-server=utf8 --collation-server=utf8_unicode_ci"

That successfully sets the two things I'm primarily concerned with.

If I use mysql --help to see what config files I'm using, which says just /etc/my.cnf (the ~/.my.cnf file doesn't exist) /etc/my.conf just includes /etc/my.cnf.d so I have included a grep rather than grinding all the files:

[digitester@server logs]$ cat /etc/my.cnf

      [client-server]
      !includedir /etc/my.cnf.d
[digitester@server logs]$ ls /etc/my.cnf.d/

      mysql-clients.cnf   server.cnf          server.cnf.rpmsave  server.cnf.save     tokudb.cnf          
[digitester@server logs]$ grep latin1 *

(no results)
[digitester@server logs]$ grep swedish *

(no results)

I can't work out how to set collation_connection in the config files, but since it's utf8_general_ci I am not too concerned.

**Comment by DigiTester** [comment]
Sorry, one more thing. In [mysqld] I have put 
    init_connect='SET NAMES "utf8" COLLATE "utf8_unicode_ci"'
But that does not change collation_connection.

**Comment by jakoch** [comment]
Hey DigiTester,

the question you posted is not related to WPN-XM, its database configuration or this (closed) issue.
I'm sorry to disappoint you but i won't solve your configuration problem because my time is limited.
You might instead head over to StackOverflow or better to their DBA site to ask the question.
See for instance: http://dba.stackexchange.com/questions/8288/how-to-configure-global-charset-on-mysql

Regards, Jens

**Comment by DigiTester** [comment]
I'm sorry that you didn't bother to read what I wrote, since I posted a solution rather than a problem.

**Comment by jakoch** [comment]
Sorry, man, i read what you wrote.

Please try the latest version of the configuration: https://github.com/WPN-XM/WPN-XM/blob/master/configs/mariadb/my.ini
The relevant setting for the mysql server are here: https://github.com/WPN-XM/WPN-XM/blob/master/configs/mariadb/my.ini#L49

This my.ini is pretty close to the default configuration given in the manual in regard to the UTF-8 settings, see https://mariadb.com/kb/en/mariadb/setting-character-sets-and-collations/#example-changing-the-default-character-set-to-utf-8

> Apparently collation_server and character_set_server are set when the system is built, but since we just installed the default setup for Centos 6 It would appear that that is build with swedish instead of utf8. 

Yes, that are the defaults for all builds, including Windows and Centos. 
"In MariaDB, the default character set is latin1, and the default collation is latin1_swedish_ci." 
https://mariadb.com/kb/en/mariadb/setting-character-sets-and-collations/

> Unfortunately overriding that requires changing the mysqld command line

Yes, you might specify `character-set-server`, `collation-server` or `collation-connection` as arguments for any client command (startup config) to override the configuration of my.ini .
You might also add it to the client configuration section of the config.

> I can't work out how to set collation_connection in the config files, but since it's utf8_general_ci I am not too concerned.

You might set `init_connect='SET collation_connection = utf8_unicode_ci'` in the `[mysqld]` section.

```
[client]
default-character-set=utf8 

[mysql]
default-character-set=utf8

[mysqld]
init_connect='SET collation_connection = utf8_unicode_ci'
init_connect='SET NAMES utf8'
character-set-server=utf8
collation-server=utf8_unicode_ci 
skip-character-set-client-handshake
```

But this should be enough:
```
[mysqld]
character-set-server = utf8
collation-server = utf8_unicode_ci
```

Does this help you?

**Comment by DigiTester** [comment]
Thanks for the reply, and you're right but you're not really adding to what I already knew. I'm using the my.ini changes: 
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_unicode_ci 
And that solves the key part of the problem. The command line change also works, and avoids the issue I have that various system admins and DBAs like to revert the config files to the default. Which is strictly an internal issue for my company, not something that you can fix.

collation_connection does not seem to be changeable from utf8_general_ci to utf8_unicode_ci except by setting it every time after connecting. I'm going to be the ugly problem-reporter and say that I don't want to spend hours investigating the issue to produce a useful test case now that I have a 90% solution to my exact problem (viz, accept utf8_general_ci).

It does clarify that the systems I'm using are somehow very different from other MariaDB systems in that config options that should work, don't. But this a general MariaDB problem rather than being in any way connected to your work.

thanks again

**Comment by jakoch** [comment]
The initial request was `utf8` with `utf8_general_ci` to have some basic default config.
For now `utf8` with `utf8_general_ci` is added to the config and will ship with the next release.
But there is still time to decide this differently and change for v0.8.7.

The more i think about this issue, the more i realize that going with `utf8_unicode_ci` instead of `utf8_general_ci` would probably be a better default config for the stack.
On the other hand, there is also a recent movement to `utf8mb4` instead of just using `utf8`.
Then the collations are `utf8mb4_bin`, `utf8mb4_general_ci`, `utf8mb4_unicode_ci`.

We could go with `utf8mb4` + `utf8mb4_unicode_ci` as default. Should we?

The topic is up for community voting:

Whats would be a good and reasonable default configuration of the stack?
1. `utf8` with `utf8_general_ci`
2. `utf8` with `utf8_unicode_ci`
3. `utf8m4` with `utf8mb4_unicode_ci`

Please share your thoughts.

Thanks, Jens

---
References for "utf8" and "utf8mb4" switching:
  - Wordpress uses this already https://core.trac.wordpress.org/ticket/21212
  - Drupal raises the MySQL version requirement for better `utf8mb4` support 
        - https://www.drupal.org/node/2473301
        - https://www.drupal.org/node/1314214

- https://mathiasbynens.be/notes/mysql-utf8mb4
- https://stackoverflow.com/questions/2344118/utf-8-general-bin-unicode
- https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci

**Comment by klonos** [comment]
I wouldn't mind utf8/utf8_unicode_ci, but it seems that it is a subset of utf8m4/utf8mb4_unicode_ci and a lot of the projects are moving towards that. So I think if there are no issues against it, we should go with utf8mb4.

**Comment by jakoch** [comment]
Ok, here are the results of the Twitter poll.
We have a total number of **2 votes**.
- 0% utf8+unicode_ci
- 100% utf8mb4+unicode_ci

The community has decided to use utf8mb4+unicode_ci as new default setting.

Its sad that the community participation and contribution is so low.

**Comment by rrobino** [comment]
This issue is back, in 2018?  Ridiculous, that it even happened in the first place.  Did a regression occur or something?

**Comment by jakoch** [comment]
> This issue is back, in 2018? Ridiculous, that it even happened in the first place. Did a regression occur or something?

@rrobino Nope. It's solved, but i can't remeber, if the old v0.8.6 release contains these config changes. Use the Changelog, Luke.

**Comment by hajimurtaza** [comment]
How to do this in windows?

**Comment by jakoch** [comment]
By changing the mariadb configuration, like so: https://github.com/WPN-XM/software/blob/master/mariadb/config/my.ini#L49-L52

**Comment by Download** [comment]
@jakoch 

> Its sad that the community participation and contribution rate is so low.

Don't get me started on this.

Once upon a time (as in, somewhere in the previous milennium), some important dev at MySQL lived in sweden.... And thus, millions and millions of MySQL databases have been created with `latin1_swedish_ci` as the default collation.

This was a disaster of course as it probably took hundreds of millions of bugs and bug reports across all these databases for all the devs behind these databases to discover this insane default and convert all these databases to utf8.

But at least that fixed it right? Well, actually, no. You see, the MySQL devs had pulled another, much more devious trick on the world. They implemented utf8 as a variable length encoding, just like the 'real' utf8, but with a maximum byte length of 3 instead of 4. This created a very subtle bug, where all of the characters inside the basic multilingual plane worked, but all other characters outside of it (like this one 😢 ) actually *still* break.

And so the world spent another hundred million or so bug reports and dev hours chasing the wild 'my character is mangled' goose. 

And then you post a screenshot showing all table collations set to (mysql's crippled version of) `utf8` and say you cannot reproduce....

😢 

Do you really need a poll to figure out that the default encoding for *everything* should be `utf8mb4`, *always*?
