### ISSUE TITLE
WPN-XM for Ubuntu

### ISSUE THREAD

**Issue by tanbir2013** [WPN-XM/WPN-XM#468]
Hello concern,
I used it in my windows OS.Recenlty,I have changed my OS from windows xp to Ubuntu 14.04 LTS(64bit).
I want to use this lovely software in my current system.
Do you have any version of this software for Linux?

Let me inform ASAP.

Best Regards,
Tanbir H.
Lecturer
Department of ECE
Dhaka Engineering Institute

**Comment by jakoch** [comment]
Thank you for your question.
Unfortunately, there isn't a version of this software for Linux.
One would have to write it first...

On the other hand, it shouldn't be a problem to install the packages individually, given the fact that Debian based system have a strong package management infrastructure. You could probably install 90 percent of the software bundled in WPN-XM with an apt-get one-liner (the rest is configuration and a GUI interface).

Regards, Jens

**Comment by tanbir2013** [comment]
If I want to write this WPN-XM for Ubuntu,How can I make it?

**Comment by jakoch** [comment]
Good question. :)

Well, the goal would be to get a self-extracting package, something like the installers we have for Windows. The basic bundling could be done with makeself. The result would be a `.run` file. So the base concept for a self-extracting installer on Linux could look like this:

- Firstly, one would have to fetch all components, but this time as tar.gz archives and not their Windows counterparts (exe/zip).
- Secondly, one would have to write an installer script (bash), which does the installation of the individual components and provides some additional glue-ing (like applying and modifying configurations, so that things start to work with each other and run out of the box).
This bash script is executed automatically, after all components are extracted to the temp folder during self-extraction.
- Thirdly, build the self-extracting archive - by combining all packages with the install script.
`makeself.sh /home/wpnxm/packages wpnxm-for-linux.run "WPN-XM for Linux" ./install`

But like always the devil is within the details.

For instance, for the first step: the fetching packages into a folder, we would have to introduce a new registry containing the components and their download sources.
In order to maintain this information automatically, we need to change the updater to include not only the windows packages during crawling of vendor sites for version information, like we have it now, but take the linux archives into account. Based on that new linux registry we can then automate the downloading of packages into the packaging folder.

For step two, the installer script, we might transfer some installation commands used in the InnoSetup scripts over to bash, but it's probably close to a rewrite. Same for the batch helper scripts.

Additionally some changes to WPN-XM components are required.

The webinterface should work on Linux, because it's PHP, but the Windows related parts must be adjusted, like paths to config files, the start and stop commands.

A lot of changes to the Server Control Panel are required. In general targeting another platform is no problem, because its written in Qt. A core functionality here is the TrayMenu and one would need to find an alternative for a tray. And all windows specific parts, like paths, start and stop commands would additionally need their linux counterparts.

**Comment by tanbir2013** [comment]
Thanks.I am beginner in Ubuntu and so I can not write these installer
script at now,I have to use individual component.If you can make it
for Linux lover,it will be great work and inform me,I will offcourse
download and use it.

On 9/8/15, Jens A. Koch <notifications@github.com> wrote:
> Good question. :)
>
> Well, the goal would be to get a self-extracting package, something like the
> installers we have for Windows. The basic bundling could be done with
> makeself. The result would be a `.run` file. So the base concept for a
> self-extracting installer on Linux could look like this:
>
> - Firstly, one would have to fetch all components, but this time as tar.gz
> archives and not their Windows counterparts (exe/zip).
> - Secondly, one would have to write an installer script (bash), which does
> the installation of the individual components and provides some additional
> glue-ing (like applying and modifying configurations, so that things start
> to work with each other and run out of the box).
> This bash script is executed automatically, after all components are
> extracted to the temp folder during self-extraction.
> - Thirdly, build the self-extracting archive - by combining all packages
> with the install script.
> `makeself.sh /home/wpnxm/packages wpnxm-for-linux.run "WPN-XM for Linux"
> ./install`
>
> But like always the devil is within the details.
>
> For instance, for the first step: the fetching packages into a folder, we
> would have to introduce a new registry containing the components and their
> download sources.
> In order to maintain this information automatically, we need to change the
> updater to include not only the windows packages during crawling of vendor
> sites for version information, like we have it now, but take the linux
> archives into account. Based on that new linux registry we can then automate
> the downloading of packages into the packaging folder.
>
> For step two, the installer script, we might transfer some installation
> commands used in the InnoSetup scripts over to bash, but it's probably close
> to a rewrite. Same for the batch helper scripts.
>
> Additionally some changes to WPN-XM components are required.
>
> The webinterface should work on Linux, because it's PHP, but the Windows
> related parts must be adjusted, like paths to config files, the start and
> stop commands.
>
> A lot of changes to the Server Control Panel are required. In general
> targeting another platform is no problem, because its written in Qt. A core
> functionality here is the TrayMenu and one would need to find an alternative
> for a tray. And all windows specific parts, like paths, start and stop
> commands would additionally need their linux counterparts.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/WPN-XM/WPN-XM/issues/468#issuecomment-138355375


-- 
 Best Regards,
 Engr.Tanbir Hasan
 Lecturer,Dhaka Engineering Institute
 Dhaka,Bangladesh

**Comment by jakoch** [comment]
Its possible, but a lot of work.  
But, given the amount of contributions i get (zero), i have to focus on the important stuff.

Ubuntu has package management (apt-get). Settings things up is a matter of seconds.
The only thing missing is the Control Panel.

Bottom line: I drop this idea. Will not implement.
