### ISSUE TITLE
v0.8.6 Webinstaller phpext_wincache.zip 

### ISSUE THREAD

**Issue by fruor** [WPN-XM/WPN-XM#531]
Now I tried v0.8.6 and there I get a 404 with phpext_wincache.zip

thank you for the fast fix earlier today, that was with v0.8.5

**Comment by jakoch** [comment]
Thank you again for reporting the issue. 
The registry is out-of-sync.
The last update for phpext_wincache messed the registry up.
https://github.com/WPN-XM/registry/commit/53702b39d7ee4ea9ef4202514f956b5d8638d29f#diff-90bf5e8b31d4328245821666bd64b974

Thats mainly because the crawler fetches the latest version from PECL without any precautions for crappy releases on their side. But they release very inconsistently, see
http://windows.php.net/downloads/pecl/releases/wincache/1.3.7.7/ - 5.3,5.4,5.5,5.6
http://windows.php.net/downloads/pecl/releases/wincache/2.0.0.1/ - 7.0

**quick fix**
The quick fix is to lower the version of phpext_wincache to v1.3.7.7.
That will make it work with the released webinstallers and the PHP version 5.4, 5.5, 5.6.
But won't work with the upcoming webinstaller for PHP7 (which needs 2.0.0.1).

**real fix**
This needs a really performance draining patch on the `get.php` script to forward to the right download URLs. 

For PHP7 we need to redirect to the **real latest version** (v2.0.0.1). 

   - http://wpn-xm.org/get.php?s=phpext_wincache&p=7.0&bitsize=x64

For all other PHP versions redirect to the **latest available version** (v1.3.3.7).
   - http://wpn-xm.org/get.php?s=phpext_wincache&p=5.4&bitsize=x64
   - http://wpn-xm.org/get.php?s=phpext_wincache&p=5.5&bitsize=x64
   - http://wpn-xm.org/get.php?s=phpext_wincache&p=5.6&bitsize=x64

Quick fix incoming...

**Comment by jakoch** [comment]
Marking this issue as blocker for PHP 7 webinstallers.

**Comment by jakoch** [comment]
Resolved the blocker situation for PHP 7 webinstallers by **removing the extension from all installers**.
https://github.com/WPN-XM/WPN-XM/issues/533
