### ISSUE TITLE
How to Change port?

### ISSUE THREAD

**Issue by alisiddique** [WPN-XM/WPN-XM#554]
Hi There,

How to change localhost port and mysql port? XAMP already installed on my machine. Can i use both?

**Comment by jakoch** [comment]
Hey Ali,

first off, thank you for downloading and testing this stack. 

- You need to change the ports manually.
In case you are starting with the batch files, then you need to change the ports in `start.bat`.
If you start using the SCP, then you need to tweak the ports in `wpn-xm.ini`.

- The "How to change ports?" question comes up a lot, mainly because the Server Control Panel still misses a GUI for it. We still have an open ticket for this feature: #327 ("add Config Tab for port configuration"). Because of your request and the high-number of requests for this feature in general, i've re-scheduled the ticket and added it to the v0.8.7 milestone (next version). 

> XAMP already installed on my machine. Can i use both?

Well, when the port collisions are resolved, both stacks _could possibly_ work next to each other.

Important: You will run into a shutdown problem, when using our batch file for stopping the servers. It uses `taskkill` and will kill all processes, including the ones from the other stack. 

----

Please allow a question: 
What are missing features of WPN-XM when compared to XAMPP from your point of view?

Best, Jens

**Comment by alisiddique** [comment]
Hi Jens,

Thanks for quick reply. WPN-XM features are nice. Hope configuration dialog will be added soon. Changed port both start.bat and wpn-xm.ini some feature not starting.
MariaDB:
MongoDB
Memcached
[log.zip](https://github.com/WPN-XM/WPN-XM/files/244880/log.zip)

**Comment by alisiddique** [comment]
![capture](https://cloud.githubusercontent.com/assets/4035727/14952893/6eb01cbe-1086-11e6-98b4-ef52fcd99cb4.PNG)
Still showing 80 and 3306 port.

**Comment by jakoch** [comment]
Thank you for the detailed report.

Ok, lets see:

**MongoDB**
- `User Assertion: 28663:Cannot start server. The default storage engine 'wiredTiger' is not available with this build of mongod. Please specify a different storage engine explicitly, e.g. --storageEngine=mmapv1.`
This doesn't sound like a port problem, but more like a configuration issue.
- [Port for Mongo is configured in `mongodb.conf`](https://github.com/WPN-XM/software/blob/master/mongodb/config/mongodb.conf#L15)
- I've checked the SCP start command for MongoDb. `mongodb.conf` is used, see https://github.com/WPN-XM/server-control-panel/blob/690983a9f444d547b3c044c8e7487f00f76eebb1/src/servers.cpp#L591
- If this is not port change related, then we need to find a configuration fix...

**MariaDB**
- `Unknown/unsupported storage engine: innodb`
The same here: doesn't sound like a port problem, but more like a configuration issue.
- I've checked ini usage on the start command of the SCP
  my.ini is used in the SCP, see https://github.com/WPN-XM/server-control-panel/blob/690983a9f444d547b3c044c8e7487f00f76eebb1/src/servers.cpp#L508-L509
- If this is not port change related, then we need to find a configuration fix...

**Memcached**
- no log attached
- port config is in start.bat
- i messed the start command for Memcached up in the SCP - **This is a bug.** :bug: 
  - https://github.com/WPN-XM/server-control-panel/blob/690983a9f444d547b3c044c8e7487f00f76eebb1/src/servers.cpp#L641
  - this means its starting the exe, but without further config
  - the SCP should do the same as the `start.bat/run.bat`
    - https://github.com/WPN-XM/WPN-XM/blob/master/startfiles/run.bat#L57
    - `bin\memcached\memcached.exe -p 11211 -U 0 -t 2 -c 2048 -m 2048`

**MainWindow - Still showing 80 and 3306 port.**

Maybe i forgot to fetch the number ? Need to check that..

**Comment by alisiddique** [comment]
Thanks for reply.

**Comment by jakoch** [comment]
Ok, i found several bugs and configuration issues.
I hope i can address these issues properly for the next release.

I've opened a new issue for the "netstat / process oveview" feature request.
It seems its a `netstat` or `netstat -abno` output in a table. Lets add that.

**Comment by jakoch** [comment]
Regarding the MariaDB `Unknown/unsupported storage engine: innodb` problem:
- I can't relate it to a config issue or start or stop command bug.
- this is either due to multiple mysqld daemons running on different ports
- or an unclean shutdown, which messed the ibdata file up
   - see `mariadb_error.log` with messages:
       - `Database was not shutdown normally!`
       - `Starting crash recovery.`

The MariaDB shutdown should be:
`bin\mariadb\bin\mysqladmin --defaults-file=bin\mariadb\my.ini -uroot -h127.0.0.1 --protocol=tcp shutdown`. I think i added this for v0.8.6 to the SCP and the batch files. That means i can exclude a problem with the stopCommand.

I could imagine two possible fixes: 
- InnoDB recovery run 
- or removal/delete of logs and ibdata files and a fresh MariaDB init to start a new database.
