### ISSUE TITLE
WP Permalinks

### ISSUE THREAD

**Issue by sierrab123** [WPN-XM/WPN-XM#602]
Install worked a treat, wordpress runs superbly in folder www/nginxshopp/

Running on Win 10

That is the wordpress folder is named nginxshopp and runs as it should with default permalinks

I switch to Pretty Permalinks (Post Name in this case) and 404's result.

I have tried adding

location /nginxshopp/ {
    try_files $uri $uri/ /nginxshopp/index.php?$args;
}

and

location /nginxshopp {
      index index.php;
if (!-e $request_filename) { rewrite ^(.+)$ nginxshopp/index.php?q=$1 last;

}

to the nginx.conf file, all to no avail.

With the former I get an index of the pages

Rather than attempt a full reinstall as per your answer here https://github.com/WPN-XM/WPN-XM/issues/393

Is there a solution that does not involve nginxshopp.dev?

**Comment by jakoch** [comment]
Hey!

> Is there a solution that does not involve nginxshopp.dev?

Yes, there is. I think, you are already on the right track. 
You would add an additional `location` section to the main `server` block in `nginx.conf`.
That's the one, which serves `localhost`.

Your first location block looks ok to me! It should enable short URLs for Wordpress, like `http://localhost/wordpress/2016/02/hello-world/`:

```
location /wordpress {
    try_files $uri $uri/ /wordpress/index.php?$args;
} 
```

> With the former I get an index of the pages

Ah..wait..... you get the listing only, when there is no `index.php`.
Wordpress has an `index.php`. 
I assume, that you installed "shopp" into the folder `/www/nginxshopp`, right?
When the application is not a standalone application, but a plugin for Wordpress, 
you would need to drop it into the wordpress plugin folder.
`C:\server\www\wordpress\wp-content\plugins\shopp`.

Please move the files there, then check in the WP backend, if it's possible to activate the plugin.
That also means that plugin doesn't have it's own rewrite rule configuration, 
because the one from Wordpress applies.

You can rename the "wordpress" folder to "wp-shopp" and adjust the location accordingly, 
to get another URL, e.g. `http://localhost/wp-shopp`.

Is this ok?

Best, Jens

**Comment by jakoch** [comment]
Hmm, when i activate the plugin i get an installation error...

```
Fatal error: Uncaught Error: Call to undefined function mysql_error() in C:\server\www\wordpress\wp-content\plugins\shopp\core\flow\Install.php on line 219
( ! ) Error: Call to undefined function mysql_error() in C:\server\www\wordpress\wp-content\plugins\shopp\core\flow\Install.php on line 219
```

That's because mysql_error is deprecated since PHP5.5.0 and i'm running PHP7.
The requirements for Shopp are not correct: ""5.2 or higher", it's "5.2 to 5.4". 
Need to install a 5.4 and will test the installation tomorrow...

**Comment by sierrab123** [comment]
Hi Jens,

Thanks for taking a look, I will try these suggestions out in the morning....

In the meantime, I did follow your absolutely perfect instructions for setting up a site using the wordpress.dev solution and have that running on localhost now with pretty permalinks working with no issue

I had no issues installing Shopp on that and it is running now

Incidentally, I also have Shopp running on a site using PHP version 7.0 and I have several sites running Shopp on 5.6

Please do not spend any more of your valuable time on this issue. I will be able to take it from here. Thank you

I did originally try the wpn-xm php 7.0 version but found that I had issues with adminer (and noted it my uninstall reply) and so went down to the 5.6 which is a real treat to work with.

Congratulations on a very fine piece of development

**Comment by jakoch** [comment]
>  Please do not spend any more of your valuable time on this issue. I will be able to take it from here. Thank you

You are welcome. 

> I did originally try the wpn-xm php 7.0 version but found that I had issues with adminer (and noted it my uninstall reply) and so went down to the 5.6 which is a real treat to work with.

Yes, i got a few reports about incompatibility. At the time of packaging Adminer had a few issues with 7. It's latest version should run fine.

> Congratulations on a very fine piece of development

Glad you like it (, despite the fact that it's still a vZero product with a lot of issues.)
