### ISSUE TITLE
MongoDB Can't start

### ISSUE THREAD

**Issue by lovebdsobuj** [WPN-XM/WPN-XM#603]
MongoDB Can't start

```
2016-08-04T18:03:17.750+0600 D -        [main] tcmallocPoolSize: 1073741824
2016-08-04T18:03:17.755+0600 D -        [initandlisten] User Assertion: 28663:Cannot start server. The default storage engine 'wiredTiger' is not available with this build of mongod. Please specify a different storage engine explicitly, e.g. --storageEngine=mmapv1.
2016-08-04T18:03:17.755+0600 I STORAGE  [initandlisten] exception in initAndListen: 28663 Cannot start server. The default storage engine 'wiredTiger' is not available with this build of mongod. Please specify a different storage engine explicitly, e.g. --storageEngine=mmapv1., terminating
2016-08-04T18:03:17.755+0600 I CONTROL  [initandlisten] dbexit:  rc: 100

```

https://gist.github.com/lovebdsobuj/da1887749342cf6bc4e4e8525c697c87

I tried with this command,
`mongod --dbpath "data" --storageEngine "mmapv1"`

But not yet done.

**WPN-XM** `v0.8.5+0a7e025`
**Windows 10** (`32 bit`)

---

:tulip:  Another talk I forgot to write maybe I'm going to love **WPИ-XM Server Stack** as my Favourite Localhost Webserver. :tulip:

**Comment by jakoch** [comment]
Hey! 
Thank you for the issue report and your kind words.

This problem was reported before (in #554) and i created a standalone, but empty ticket for it (#556).
It's  a duplicate, but your ticket has the better content, because of the attached logs and details.
Thank you for that.

**How could a possible solution look like?**

The MongoDB manual states that the change of the default engine was introduced for `3.2`,
see https://docs.mongodb.com/manual/release-notes/3.2-compatibility/#default-storage-engine-change - but actually, things break in earlier development versions like `3.1.7`.

One way of getting the engine support right, is to alter the start command in the SCP
The other way is to alter the configuration file.

The start command looks like this: https://github.com/WPN-XM/server-control-panel/blob/317a526d49b3bbcd5d936757accb6f40dc801eab/src/servers.cpp#L582-L587
We are using a config file, but we are not setting the storageEngine explicitly.

We can do two things:
- We could execute `mongod --version` one time internally to get the version and the bitsize -
and then based on that information, either set the `--storageEngine` to `"mmapv1"` or `"wiredTiger"`.
- Or we adjust the engine in the configuration file.

The v0.8.6 config doesn't include the storage engine setting, see https://github.com/WPN-XM/WPN-XM/blob/v0.8.6/configs/mongodb/mongodb.conf

It's also not set in the config for the upcoming version, but i could add that.
https://github.com/WPN-XM/software/blob/master/mongodb/config/mongodb.conf

I've also worked an the configuration dialog and it as a dropdown directive, but it needs some more love to be ready.
![mongodb-config](https://cloud.githubusercontent.com/assets/85608/17405744/06601d92-5a61-11e6-8db1-6d4b9a51ca31.jpg)

I will add the storageEngine to the config manually and check with the latest MongoDb version to see, if that works.

**Comment by jakoch** [comment]
**Workaround**
Please adjust your `mongodb.conf` file
and specify a different storage engine explicitly, e.g. `--storageEngine=mmapv1`.

**Comment by lovebdsobuj** [comment]
It's work.

**Comment by jakoch** [comment]
The new MongoDb configuration dialog allows to select the engine.
The value is written to the configuration file.
The configuration file is used on the start command.

![mongo-change-engine](https://cloud.githubusercontent.com/assets/85608/20775073/782c0e0e-b759-11e6-86b4-3dbacfd4f658.png)
