### ISSUE TITLE
unpacking process failed

### ISSUE THREAD

**Issue by tobiasfichtner** [WPN-XM/WPN-XM#620]
##### Problem description

C:\Users\Service\AppData\Local\Temp\is-193G9.tmp>stripdown-mariadb.bat D:\WPN-XM\bin\mariadb
Folder "D:\WPN-XM\bin\mariadb" exists, but is not the MariaDB folder.

[-] MariaDB stripdown failed.

Drücken Sie eine beliebige Taste . . .
##### Expected behavior

run and finish WPNXM-0.8.6-Webinstaller-Setup-php55-w32.exe / -w64.exe 
run with and without administration rights
##### Possible solution

unknown

[Setup Log 2016-10-30 #001.txt](https://github.com/WPN-XM/WPN-XM/files/560501/Setup.Log.2016-10-30.001.txt)

**Comment by jakoch** [comment]
Hello Tobias!

Thank you for reporting the issue and the attached log.

The error message comes from the stripdown script for mariadb.
It seems that `D:\WPN-XM\bin\mariadb\bin\mysqld.exe` is missing.
The underlying issue might be an extraction issue with the downloaded MariaDb package 
or due to a changed directory layout of the package.

Regards, Jens

**Comment by jakoch** [comment]
I fixed the get script. So it might have been a download issue.
After that i tested a minimal installation using WPNXM-0.8.6-Webinstaller-Setup-php55-w32.exe

![webinstall-086-55-w32](https://cloud.githubusercontent.com/assets/85608/19838923/3d769fa6-9ed9-11e6-8802-04fffd598578.png)

Please give me feedback, if you are still running into this issue or if it is resolved.
Thanks, Jens

**Comment by jakoch** [comment]
Works for me. Closing.
