### ISSUE TITLE
PHP 5.6 X64 webinstaller 404

### ISSUE THREAD

**Issue by RHITNL** [WPN-XM/WPN-XM#628]
##### Problem description
Hi again.
When trying to download the PHP 5.6 X64 webinstaller from http://wpn-xm.org/ I also get a 404
The URL for that is https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Webinstaller-Setup-php56-w64.exe

##### Expected behavior
Make it work :)

##### Possible solution
Update URL to the correct file I guess

**Comment by jakoch** [comment]
> Update URL to the correct file I guess
Damn. Updating the URL won't work, because that's a missing installer file. 
Seems it wasn't released at all: https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.6
I wonder why nobody reported that before.

Ok, i need to check the release log and see what happened back then.
Maybe it wasn't build correctly or the upload to Github Releases failed.
Info upcoming.

**Comment by jakoch** [comment]
The installer wasn't released, because the innosetup script file had a syntax error:
https://travis-ci.org/WPN-XM/WPN-XM/builds/76626703#L5876

To avoid this scenario i need add another build step, which needs to make sure 
that setup executables are build for all the ISS files - and otherwise fails the build.

- [ ] build step: check all `iss` files have an `exe` after innosetup compilation step
