### ISSUE TITLE
Wordpress Permalinks not functioning as before

### ISSUE THREAD

**Issue by sierrab123** [WPN-XM/WPN-XM#635]
##### Problem description
Using the method outlined here (https://github.com/WPN-XM/WPN-XM/issues/393) I was able to run the program with no issues since 2016 (on and off), permalinks etc working fine

I tried yesterday and found that something seems to have changed in win 10 as I needed to change the config so that it used port 8070

Easy to do and I made the relevant changes in hosts, nginx.config, wordpress.conf so that it would use 8070

Firefox can’t find the server at wordpress.dev. when I go to http://wordpress.dev/wp-admin/setup-config.php

The non dev site functions as expected

The control panel interface continues to show nginx using 80 https://puu.sh/too4C/16c9dec947.png

Belated happy new year

**Comment by jakoch** [comment]
Hey!
Thank you for the issue report.

> Easy to do and I made the relevant changes in hosts, nginx.config, wordpress.conf so that it would use 8070

That won't work! Because the `hosts` file can't handle ports. It only resolves names.

before: `127.0.0.1                 wordpress.dev`
after:     `127.0.0.1:8070       wordpress.dev` // invalid syntax 

>Firefox can’t find the server at wordpress.dev

The invalid hosts file entry is the reason.

You could use the browser to select the port.
For instance with by using a bookmark `http://wordpress.dev:8070/`, which resolves to `127.0.0.1:8070`.
This is of course a workaround.

I guess, the real solution to your issue would mean to find out, why WP isn't served anymore at the old port.

> The control panel interface continues to show nginx using 80
That's a bug of the SCP. It's already fixed and ships with the next version.
It will display the port(s) and names used in Nginx's config file.
I've prepared a tooltip overlay. It's a tiny display, which shows all "port to servername" relations.

> Belated happy new year
Thank you! And also to you!

Regards, Jens

**Comment by sierrab123** [comment]
For any others having this issue I found the cause to be MsDepSvc which is the web deployment service

**Comment by jakoch** [comment]
Thank for the feedback. I've updated the FAQ accordingly.

**Comment by sierrab123** [comment]
Credit where credit is due, http://www.devside.net/wamp-server/opening-up-port-80-for-apache-to-use-on-windows

Best article on port 80 issues I found, after much Googling.
